Traceback (most recent call last):
  File "snippet.py", line 79, in <module>
    for table in get_mysql_tables():
  File "snippet.py", line 70, in get_mysql_tables
    cursor = create_mysql_connection()
  File "snippet.py", line 65, in create_mysql_connection
    conn = MySQLdb.connect(**MYSQL)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
