Traceback (most recent call last):
  File "snippet.py", line 29, in <module>
    PATH_TO_FILE = sys.argv[1]
IndexError: list index out of range
