Traceback (most recent call last):
  File "snippet.py", line 46, in <module>
    config.readfp(open('pyvmomi_defaults.cfg'))
IOError: [Errno 2] No such file or directory: 'pyvmomi_defaults.cfg'
